# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.15

CUDF_DIR := /home/dbaranec/projects/cudf/cpp
RMM_DIR := /home/dbaranec/projects/rmm

# compile CUDA with /usr/local/cuda/bin/nvcc
# CUDA_FLAGS =  -lineinfo -Xptxas -O3 -Xcompiler -O3 -gencode arch=compute_60,code=sm_60 -gencode arch=compute_70,code=sm_70 -gencode arch=compute_75,code=sm_75 -gencode arch=compute_75,code=compute_75 --expt-extended-lambda --expt-relaxed-constexpr -DJITIFY_USE_CACHE -DCUDF_VERSION=0.13.0 -std=c++14
CUDA_FLAGS =  -lineinfo -gencode arch=compute_60,code=sm_60 -gencode arch=compute_70,code=sm_70 -gencode arch=compute_75,code=sm_75 -gencode arch=compute_75,code=compute_75 --expt-extended-lambda --expt-relaxed-constexpr -DJITIFY_USE_CACHE -DCUDF_VERSION=0.13.0 -std=c++14

CUDA_DEFINES = -DARROW_METADATA_V4

CUDF_INCLUDES = -I$(CUDF_DIR) -I$(CUDF_DIR)/include -I$(CUDF_DIR)/build/googletest/install/include -I$(CUDF_DIR)/build/googlebenchmark/install/include -I$(CUDF_DIR)/build/_deps/thrust-src -I$(CUDF_DIR)/build/_deps/jitify-src -I$(CUDF_DIR)/build/_deps/libcudacxx-src/include -I/usr/local/cuda/targets/x86_64-linux/include -I$(CUDF_DIR)/build/include -I$(CUDF_DIR)/build/include/jit -I$(CUDF_DIR)/include -I$(CUDF_DIR)/src -I/home/dbaranec/miniconda3/envs/cudf_dev/include


